# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    owl_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

owl_controller:
  ros__parameters:
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
    command_interfaces:
      []
    state_interfaces:
      []